# Porfolio deployment tasks.
# Date created: 8-21-2020
# Modified on 5-8-2021 to host the site-under-construction page.
# Refactored command to /bin/cp -R * $DEPLOYPATH

---
    deployment:
        tasks:
            - export DEPLOYPATH=/home/dylancro/public_html/
            - /bin/cp -R * $DEPLOYPATH
# End of file